name: Brandon Holt
description: Potentially helpful tips and tricks I've learned or made up.
markdown: redcarpet
highlighter: pygments

redcarpet:
    extensions: ["with_toc_data"]

# gems:
#   - jekyll-knitr
  
keep_files:  ['.git','fig/']

knitr:
  chunk_options:
    fig.width: 5
    fig.height: 4
    fig.path: 'fig/'
    dev: svg

base: ''

url: http://homes.cs.washington.edu/~bholt/

permalink: /posts/:title.html

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: home
      link: /
    - title: projects
      link: /projects.html
    - title: cv
      link: /cv.html
    - title: posts
      link: /posts.html
    - title: 
      link: http://github.com/bholt
      icon: /img/GitHub-Mark-24px.png
    - title: 
      link: http://twitter.com/holtbg
      icon: /img/twitter_logo_blue.png
