name: Brandon Holt
markdown: redcarpet  
pygments: true

base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Projects
      link: /projects.html
    - title: Curriculum Vitae
      link: /cv.html
