name: Brandon Holt
markdown: redcarpet  
pygments: true

base: ''

exclude: [README.md]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Projects
      link: /projects.html
    - title: Curriculum Vitae
      link: /cv.html
    - title: Github
      link: https://github.com/bholt
      icon: /img/GitHub-Mark-32px.png
