name: Brandon Holt
description: Potentially helpful tips and tricks I've learned or made up.
markdown: redcarpet
highlighter: pygments

redcarpet:
    extensions: ["with_toc_data"]

# gems:
#   - jekyll-knitr
#   - 'jekyll-pandoc-multiple-formats'
gems: ['jekyll/scholar']

keep_files:  ['fig']

knitr:
  # opts_knit:
  #   base.dir: '_site/fig/'
  opts_chunk:
    fig.width: 5
    fig.height: 4
    fig.path: 'fig/'
    echo: FALSE
    message: FALSE
    warning: FALSE
    error: FALSE
    dev: svg

# pandoc:
#   skip: true
#   impose: false
#   output: ./tmp
#   flags: '--smart --bibliography=_data/refs.bib --csl=_data/ieee.csl'
#   # site_flags: '--toc'
#   outputs:
#     pdf: '--latex-engine=latex'
#   #   epub:
#   #   markdown:

scholar:
  style: ieee
  locale: en

  sort_by: none
  order: ascending

  source: ./_data
  bibliography: refs.bib
  bibliography_template: |
    {{reference}}

  replace_strings: true
  join_strings:    true

  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  # query: "@*"

base: ''

url: http://homes.cs.washington.edu/~bholt/

permalink: /posts/:title.html

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Projects
      link: /projects.html
    - title: CV
      link: /cv.html
    - title: Posts
      link: /posts/
    - title: 
      link: http://github.com/bholt
      icon: /img/GitHub-Mark.png
      icon2x: /img/GitHub-Mark@2x.png
    - title: 
      link: http://twitter.com/holtbg
      icon: /img/twitter-logo.png
      icon2x: /img/twitter-logo@2x.png
