name: Brandon Holt
markdown: redcarpet  
pygments: true

base: ''

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Projects
      link: /projects.html
    - title: CV
      link: /cv.html
    - title: Posts
      link: /posts.html
    - title: 
      link: https://github.com/bholt
      icon: /img/GitHub-Mark-32px.png
