name: Brandon Holt
description: Potentially helpful tips and tricks I've learned or made up.
markdown: redcarpet
highlighter: pygments

redcarpet:
    extensions: ["with_toc_data"]

gems:
#   - jekyll-knitr
  - 'jekyll-pandoc-multiple-formats'
  
keep_files:  ['fig']

knitr:
  # opts_knit:
  #   base.dir: '_site/fig/'
  opts_chunk:
    fig.width: 5
    fig.height: 4
    fig.path: 'fig/'
    echo: FALSE
    message: FALSE
    warning: FALSE
    error: FALSE
    dev: svg

pandoc:
  skip: true
  impose: false
  output: ./tmp
  flags: '--smart --bibliography=refs.bib'
  # site_flags: '--toc'
  outputs:
    pdf: '--latex-engine=latex'
  #   epub:
  #   markdown:

base: ''

url: http://homes.cs.washington.edu/~bholt/

permalink: /posts/:title.html

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: home
      link: /
    - title: projects
      link: /projects.html
    - title: cv
      link: /cv.html
    - title: posts
      link: /posts/
    - title: 
      link: http://github.com/bholt
      icon: /img/GitHub-Mark.png
      icon2x: /img/GitHub-Mark@2x.png
    - title: 
      link: http://twitter.com/holtbg
      icon: /img/twitter-logo.png
      icon2x: /img/twitter-logo@2x.png
