name: Brandon Holt
markdown: redcarpet  
pygments: true

base: ''

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: Home
      link: index.html
    - title: Projects
      link: projects.html
    - title: Curriculum Vitae
      link: cv.html
    - title: Github
      link: https://github.com/bholt
      icon: img/GitHub-Mark-32px.png
