name: Brandon Holt
markdown: redcarpet  
pygments: true

base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people.html
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Code
      link: /code.html
